id: P45074C92
initial_creation_type: input
source_metadata:
  Title: Balim훮lik훮
  Editor: Sumatisimha
  Publisher: '-'
  Place of Publication: Japan
  Year: '1967'
  Balim훮lik훮:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:10:13.112914'
last_modified_at: '2022-03-08T17:10:13.112922'
